<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Confirma a exclusão?',
    'Clientes' => 'Clientes',
    'Create' => 'Adicionar',
    'Create Clientes' => 'Adicionar Clientes',
    'Create Cotacao' => 'Criar Cotação',
    'Create Ordem Coleta' => 'Gerar Ordem de Coleta',
    'Create Fatura' => 'Gerar Fatura',
    'Create Veiculos' => 'Adicionar Veículo',
    'Create Tabelas' => 'Adicionar Tabelas',
    'Create Minutas' => 'Emitir Minutas',
    'Create Seguro' => 'Informar seguro',
    'Create Funcionarios' => 'Adicionar Funcionários',
    'Create Cte' => 'Emitir Conhecimento',
    'Create Mdfe' => 'Emitir Manifesto',
    'Create Veiculos Abastecimento' => 'Novo abastecimento',
    'Create Veiculos Servico Tipo' => 'Novo tipo de serviço',
    'Create Veiculos Servico' => 'Novo serviço/despesa',
    'Create Fatura Boleto' => 'Novo Boleto',
    'Mdves' => 'Manifestos',
    'Veiculos Abastecimentos' => 'Frota - Abastecimento',
    'Veiculos Servico Tipos' => 'Frota - Tipos de serviço',
    'Veiculos Servicos' => 'Frota - Serviços / Despesas',
    'Ctes' => 'Conhecimento de Transporte (CT-e)',
    'Cotacaos' => 'Cotações',
    'Ordem Coletas' => 'Ordem de Coleta',
    'Delete' => 'Excluir',
    'Reset' => 'Resetar',
    'Search' => 'Procurar',
    'Update' => 'Atualizar',
    'Save' => 'Salvar',
    'Update {modelClass}: ' => 'Atualizar {modelClass}: ',
    'Create {modelClass}: ' => 'Adicionar {modelClass}: ',
];
